# Generated by Django 3.2.8 on 2021-11-01 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0005_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='lk',
            name='project_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='log.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='push',
            name='project_name',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='log.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sms',
            name='project_name',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='log.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spnavigator',
            name='project_name',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='log.project'),
            preserve_default=False,
        ),
    ]
